from dotenv import load_dotenv
from langgraph.graph import MessagesState, END #imports the standard state shape and the END node signal
from langgraph.prebuilt import ToolNode #imports LangGraph's pre-built node that automatically executes tools
from langchain_core.messages import SystemMessage #imports the class for the AI's foundational instructions

from react import tools, llm_with_tools #imports our configured LLM and tool list from react.py
from prompts.system_prompts import system_prompt  #imports the text of my system prompt

load_dotenv()

SYSTEM_MSG = SystemMessage(content=system_prompt) # waps your raw prompt string into a formal SystemMessage object


class AgentNodes:
    def __init__(
        self,
        *,
        system_message: SystemMessage | None = None,
        llm_with_tools_instance=None,
        tools_list=None,
    ) -> None:
        self.system_message = system_message or SYSTEM_MSG #assign the system message
        self.llm_with_tools = llm_with_tools_instance or llm_with_tools #assigns the language model
        self.tools = tools_list or tools
        self.tool_node = ToolNode(self.tools)

    def run_agent_reasoning(self, state: MessagesState): # The function executed when the graph hits the "agent" node
        # Calls the LLM. It prepends the SystemMessage to the beginning of the conversation history (state["messages"])
        response = self.llm_with_tools.invoke([self.system_message] + state["messages"])
        # Returns the LLM's response. LangGraph will automatically append this to the state's message list.
        return {"messages": [response]}

    def should_continue(self, state: MessagesState) -> str:
        #looks at the very last message in the history (which was just generated by the LLM above)
        if not state["messages"][-1].tool_calls:
            return END # if the LLM didn't ask to use any tools, return END to stop the graph and send the answer to the user
        return "tools"# if the LLM DID ask to use a tool, return the string "tools" to route the graph to the ToolNode


_nodes = AgentNodes()
tool_node = _nodes.tool_node

# These wrapper functions are exposed so graph.py can easily import and attach them to nodes
def run_agent_reasoning(state: MessagesState):
    return _nodes.run_agent_reasoning(state)


def should_continue(state: MessagesState):
    return _nodes.should_continue(state)
